spring:
  profiles:
    active: dal,web
    thymeleaf:
      mode: HTML
      encoding: UTF-8
      servlet:
        content-type: text/html
      cache: false

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /logs/boot
      file-date-format: .yyyyMMdd
      pattern: '%h %l %u %t "%r" %s %b %Dms "%{Referer}i" "%{User-Agent}i" "%{X-Request-ID}i" "%{X-Forwarded-For}i"'
#    basedir: /logs